### ISSUE TITLE
hashi_vault: tests fail (unstable) on macOS 10.15

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/community.hashi_vault#19]
##### SUMMARY
The tests for the `hashi_vault` lookup plugin fail on macOS (added to CI in ansible-collections/community.general#971). They are currently disabled.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
plugins/lookup/hashi_vault.py

##### ANSIBLE VERSION
2.10

**Comment by dmsimard** [comment]
Hi @felixfontein, FYI I've moved this issue to the community.hashi_vault collection repository.
