### ISSUE TITLE
Investigate new failures in devel

### ISSUE THREAD

**Issue by briantist** [ansible-collections/community.hashi_vault#289]
##### SUMMARY

[Seeing some failures in daily CI today in devel](https://github.com/ansible-collections/community.hashi_vault/runs/7580395180?check_suite_focus=true#step:11:5683):

> fatal: [testhost]: FAILED! => {
>     "msg": "The conditional check 'result == {}' failed. The error was: An unhandled exception occurred while templating '{{ lookup('community.hashi_vault.vault_write', 'cubbyhole/secret1', **kwargs) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while running the lookup plugin 'community.hashi_vault.vault_write'. Error was a <class 'requests.exceptions.InvalidHeader'>, original message: Header part ('hvs.CAESIDuQk-b_84grFKHxz_B9F4sosfrNY1ci5ZmsurpX1EDzGh4KHGh2cy5pbVlsQTZBNUc4dFlzZnEzVVhRUmxUd2E') from {'X-Vault-Token': 'hvs.CAESIDuQk-b_84grFKHxz_B9F4sosfrNY1ci5ZmsurpX1EDzGh4KHGh2cy5pbVlsQTZBNUc4dFlzZnEzVVhRUmxUd2E'} must be of type str or bytes, not <class 'ansible.utils.unsafe_proxy.AnsibleUnsafeText'>. Header part ('hvs.CAESIDuQk-b_84grFKHxz_B9F4sosfrNY1ci5ZmsurpX1EDzGh4KHGh2cy5pbVlsQTZBNUc4dFlzZnEzVVhRUmxUd2E') from {'X-Vault-Token': 'hvs.CAESIDuQk-b_84grFKHxz_B9F4sosfrNY1ci5ZmsurpX1EDzGh4KHGh2cy5pbVlsQTZBNUc4dFlzZnEzVVhRUmxUd2E'} must be of type str or bytes, not <class 'ansible.utils.unsafe_proxy.AnsibleUnsafeText'>"
> }
> 

It looks like something has changed causing the result to be considered "unsafe" from various lookups.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

auth_token
lookup_hashi_vault
lookup_vault_kv1_get
lookup_vault_kv2_get
lookup_vault_login
lookup_vault_read
lookup_vault_token_create
lookup_vault_write

##### ANSIBLE VERSION

devel

##### COLLECTION VERSION

current

**Comment by briantist** [comment]
It appears that this is due to a change in `requests` unfortunately:
- https://github.com/psf/requests/issues/6159

This probably means the token returned as always being marked as unsafe anyway, or perhaps that happened after the token changes in 1.10, but either way, `requests` was turning them back into regular strings.

It seems they are reluctant to change this behavior back despite it being breaking; even if gets reverted it will probably happen again in another release.

Will have to see what we can do on our side.

**Comment by briantist** [comment]
The workaround I've been working on is to internally ensure that tokens are always strings when we pass them to the client. Hope to have a PR up for this soon.

**Comment by fansari** [comment]
I came across the same issue. The latest version I can install with pip which does not run into this bug is this:

```
pip install ansible==6.7.0
```

**Comment by briantist** [comment]
@fansari this should have been fixed in #291 in collection version `3.2.0`. When you run `ansible-galaxy collection list` what version of this collection do you see?

**Comment by deuspt** [comment]
Same issue here today in a freshly installed debian 12 box.

```
ansible [core 2.14.16]
community.hashi_vault: 6.2.0
Python 3.11.2
```

With a playbook like this:

`- name: Test hashi_vault
  hosts: localhost
  vars:
    token: "{{ lookup('env', 'VAULT_TOKEN') }}"
    address: "http://127.0.0.1:8200"

  tasks:
    - name: Debug token type
      debug:
        msg:
          - "Token: {{ token }}"
          - "Token Type: {{ token | type_debug }}"

    - name: Use hashi_vault plugin
      set_fact:
        secret_data: "{{ lookup('hashi_vault', 'secret=kv/data/test token={{ token }} url={{ address }}', token_validate=False) }}"`
        
get the following outputs:

`ok: [localhost] => {
    "msg": [
        "Token: hvs.CAESIKUDolbsx0MaibISN-3Ft4d1XAVv_McXr2ElzoSK4KCnGh4KHGh2cy4xS0laUGhOV1NHbnJINlMwM1VFdDdlTTQ",
        "Token Type: AnsibleUnsafeText"
    ]
}`

`An unhandled exception occurred while running the lookup plugin 'hashi_vault'. Error was a <class 'requests.exceptions.InvalidHeader'>, original message: Header part ('hvs.CAESIKUDolbsx0MaibISN-3Ft4d1XAVv_McXr2ElzoSK4KCnGh4KHGh2cy4xS0laUGhOV1NHbnJINlMwM1VFdDdlTTQ') from {'X-Vault-Token': 'hvs.CAESIKUDolbsx0MaibISN-3Ft4d1XAVv_McXr2ElzoSK4KCnGh4KHGh2cy4xS0laUGhOV1NHbnJINlMwM1VFdDdlTTQ'} must be of type str or bytes, not <class 'ansible.utils.unsafe_proxy.AnsibleUnsafeText'>.`

Had a remove ansible from apt and installed the version suggested above. This worked...

`pip install ansible==6.7.0 --break-system-package`

Any ideas?

Thanks

**Comment by briantist** [comment]
@deuspt I think the general consensus is to not use the version of ansible installed by OS packages, and to use a separately installed version. To do so safely without potentially breaking system packages, use a virtual environment or other form of isolation. This is more of a general ansible concern though, and you can post on https://forum.asnible.com to get more guidance on that.

It's also possible to install newer versions of collections for a given version of the `ansible` package, so you possibly could have solved this by installing a newer version of this collection while leaving the ansible install alone.

**Comment by tanji** [comment]
@briantist I don't think it has anything to do with ansible being installed with OS packages, I have a version of ansible installed with pip there and upgrading community.hashi_vault from 5.0.0 to 6.2.0  caused the issue.

Also 6.2.0 is the latest version. My ansible version is core 2.5.15.

**Comment by briantist** [comment]
> I don't think it has anything to do with ansible being installed with OS packages, I have a version of ansible installed with pip there and upgrading community.hashi_vault from 5.0.0 to 6.2.0 caused the issue.
> 
> Also 6.2.0 is the latest version. My ansible version is core 2.5.15.

@tanji 
ansible-core 2.5 is incredibly old, it does not even support collections, so I think you must be mistaken, maybe you meant 2.15? In any case I think it's best to open a new issue, or to post on the ansible forum.
