### ISSUE TITLE
Feature Request: Add possibility to get list of secrets from path

### ISSUE THREAD

**Issue by exilehanharr** [ansible-collections/community.hashi_vault#295]
##### SUMMARY

We add users to VMs and the option to pick up all secrets from some path would be good.

I've checked `hvac` python module and found that it can do this:
```python
list_response = client.secrets.kv.v2.list_secrets(
    path='hvac',
)
```
I think this option can help and other cases. If I can do this with the actual version of `hashi_vault`, could you please share the information about this?
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

hashi_vault lookup
##### ADDITIONAL INFORMATION

```yaml

```

**Comment by briantist** [comment]
Hi @exilehanharr , welcome!

We don't yet have list support but it is certainly something I want to see at some point.

My vague plans were to first introduce a generic `vault_list` (lookup and module), similar to the generic `vault_read` and `vault_write` content we have now, which helps to fill in for missing specific versions, and then to add things like `vault_kv2_list`, `vault_kv1_list`, etc., wherever it makes sense to have more specific listings.

---

If you are interested in contributing, please have a look at our [Contributor guide](https://docs.ansible.com/ansible/devel/collections/community/hashi_vault/docsite/contributor_guide.html) and let me know.

**Comment by tomkivlin** [comment]
I have a similar need for this - I will raise a PR.
