### ISSUE TITLE
✨ Feature Request: Dedicated Module for KV secrets

### ISSUE THREAD

**Issue by nwerker** [ansible-collections/community.hashi_vault#331]
##### SUMMARY

I've read through some of the issues and understand the scope of the modules and that the vault_write Module has it's particular scope and purpose. It would be nice to have a module specialized on KV secrets, with a certain behavior that makes it more suitable for some ansible tasks than the vault_write module.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Not defined yet

##### ADDITIONAL INFORMATION

This module should have the following functionality to set it apart from existing modules:
* Idempotence
* Different behaviours like
  * Update a secret (overwrite it, if content would change)
  * Append to a secret, if a new key is added for example
* Support features from KV Engine 2
  * Versioning
  * etc.

There is an existing module which implements this in quite a nice manner regarding the user experience. [Terry Howe Module](https://github.com/TerryHowe/ansible-modules-hashivault/blob/main/ansible/modules/hashivault/hashivault_secret.py), however, there are a few reasons why I wish to see such functionality in this collection!

**Comment by briantist** [comment]
Hi @nwerker !

`vault_write` was never intended to be the extent of support for writing; rather it was meant to fill gaps in the absence of dedicated content, and the plan was always to fill out the collection with those.

I spent over a year setting up the module utils for shared functionality, shoring up tests and coverage, before finally being able to add those modules and plugins in a way that makes maximum use of shared code like auth methods.

The only thing stopping me from adding all of them myself is time; I'm spread pretty thin these days.

We have a [contributor guide](https://ansible-collections.github.io/community.hashi_vault/branch/main/collections/community/hashi_vault/docsite/contributor_guide.html) to help with that, and following existing plugins and modules should also help.

It's a lot easier for me to find time to help contributor PRs than to do them myself these days.

---

For you or anyone else interested here's an example of a recent dedicated module added by a contributor:
- https://github.com/ansible-collections/community.hashi_vault/pull/304

**Comment by nwerker** [comment]
@briantist 

Completely understandable! I think this could be a good first issue / PR for new contributors.

I can empathise with the limited time, I will check within my organisation and come back to you or assign the issue to myself, when I know more!

**Comment by devon-mar** [comment]
@nwerker Are you working on this issue?
If not, I can take a look at it.

**Comment by nwerker** [comment]
@devon-mar I hadn't had the time yet, so I'd be happy if you take a look at it!
