### ISSUE TITLE
add a changelog lint job to CI

### ISSUE THREAD

**Issue by briantist** [ansible-collections/community.hashi_vault#383]
##### SUMMARY

We should run `antsibull-changelog lint` to ensure that fragments are formatted correctly.

##### ISSUE TYPE
- Feature Idea

**Comment by briantist** [comment]
hm, I forgot that sanity tests check this, is there something the lint command might catch that sanity wouldn't? @felixfontein

**Comment by felixfontein** [comment]
@briantist `ansible-test sanity` simply runs `antsibull-changelog lint`.

**Comment by briantist** [comment]
perfect, sounds like I don't need a separate job for this after all
