### ISSUE TITLE
Ansible vault, cannot escape password

### ISSUE THREAD

**Issue by janw-me** [ansible-collections/community.hashi_vault#448]
##### SUMMARY
```bash
ansible-vault encrypt_string '--IcannotCh@ngeThisPassword'
```
This command gives the following error. So it tries to read it as a normal arg.
```
ansible-vault: error: unrecognized arguments: --IcannotCh@ngeThisPassword
```
What is the correct way to escape this?
I tried:
- single quotes ''
- double quotes ""
- Tildes ``

But slashes `\` `/` these get prefixed to the password like:  
`\--IcannotCh@ngeThisPassword`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.hashi_vault

##### ANSIBLE VERSION
```console
ansible [core 2.17.1]
  config file = /home/me/Code/hosting/iffr-hosting/ansible.cfg
  configured module search path = ['/home/me/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/me/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/me/Code/hosting/iffr-hosting/collections/ansible_collections
  executable location = /home/me/.local/bin/ansible
  python version = 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

##### COLLECTION VERSION

# /home/me/.local/lib/python3.10/site-packages/ansible_collections
Collection            Version
--------------------- -------
community.hashi_vault 6.2.0  

```

##### CONFIGURATION
(tested from home dir, or whereever)
```console
CONFIG_FILE() = None
```

##### OS / ENVIRONMENT
Tested on multiple Ubuntu 22.04 servers

### Steps to Reproduce

Go to any directory and run:

```
ansible-vault encrypt_string '--IcannotCh@ngeThisPassword'
```

### Expected Results

I would expect a encrypted result (with possible password prompt)

### Actual Results

```console
usage: ansible-vault [-h] [--version] [-v] {create,decrypt,edit,view,encrypt,encrypt_string,rekey} ...
ansible-vault: error: unrecognized arguments: --IcannotCh@ngeThisPassword
```

**Comment by bcoca** [comment]
this is not related to hashicorp vault
