### ISSUE TITLE
hashi_vault - Retrieve list of secrets from path

### ISSUE THREAD

**Issue by erSitzt** [ansible-collections/community.hashi_vault#53]
##### SUMMARY

In the documentation there is this example

```
- name: Return all secrets from a path
  ansible.builtin.debug:
    msg: "{{ lookup('community.general.hashi_vault', 'secret=secret/hello token=c975b780-d1be-8016-866b-01d0f9b688a5 url=http://myvault:8200') }}"
```
This does not seem to work for me.
In the code i cant find any reference to hvac's `list` function 
```
client.secrets.kv.v2.list_secrets(mount_point="kv-v2", path="folder")
```

Am i doing something wrong, or is this a misnomer? As i understand it, the last part of the path is referred to as the "secret", which then contains keys/values.
In a path multiple secrets can exists, so "Return all secrets from a path" should list all secret-names in that path, or the complete secrets as dicts.
But currently it seems to only work when the path ends with a secret name, then listing all keys/values of that one secret... 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
hashi_vault

##### ANSIBLE VERSION

```paste below
❯ ansible --version
ansible 2.10.5
  config file = /home/buehring/GIT/srv-sftp-proxy/modules/customization/ansible/ansible.cfg
  configured module search path = ['/home/buehring/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/buehring/.local/lib/python3.6/site-packages/ansible
  executable location = /home/buehring/.local/bin/ansible
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
```

##### CONFIGURATION
Im using this part, which works fine as soon as i reference the full path to a secret, but not if i remove the last part to get a list of secrets

```paste below
  vars:
    vault_token: "{{ lookup('env', 'VAULT_TOKEN')}}"
    vault_addr: "{{ lookup('env', 'VAULT_ADDR')}}"
    vault_data: "{{ lookup('hashi_vault', 'secret=infrastructure/data/srv-sftp-proxy/allgemein token={{ vault_token }} url={{ vault_addr }}')}}"
```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by briantist** [comment]
Hi @erSitzt , I think the title of that example may need some improvement. To clarify, "secret" in the vault KV engine refers to the path itself, and the secret contains key/value pairs. That example should probably read, "return all key/value pairs from a secret".

The further clarify the behavior of the plugin: it does not support `list`ing secrets at all. In Vault API terms, this plugin only ever uses the `read` operation on a path (aside from auth related things).

Adding `list` was proposed in https://github.com/ansible-collections/community.general/pull/664 but it would add significant complexity to the plugin. Instead, I think we'll see new plugins emerge soon in the collection that will support `list` and other operations. I've started some work on the internals that should make it much easier to introduce new functionality.

---

Quick note about your example:
```
  vars:
    vault_token: "{{ lookup('env', 'VAULT_TOKEN')}}"
    vault_addr: "{{ lookup('env', 'VAULT_ADDR')}}"
    vault_data: "{{ lookup('hashi_vault', 'secret=infrastructure/data/srv-sftp-proxy/allgemein token={{ vault_token }} url={{ vault_addr }}')}}"
```
The plugin already uses `VAULT_TOKEN` and `VAULT_ADDR` directly, if the values aren't set by other means, so it's not necessary to set your `vault_token` and `vault_addr` vars unless you're trying to specifically override the precedence in place for those env vars.

**Comment by erSitzt** [comment]
Ah okay, I did not see the proposal and after looking through the code I already suspected it's only reads at the moment.
I helped myself by using a single secret and using the json to structure my data as needed.

Thanks for your note on the vault address and token 😊

Regards
Dennis

**Comment by briantist** [comment]
No worries, I'm glad you were able too find a workaround. 
I'll close this out for now. Keep an eye out for `list` support within the next couple of months if you're still interested in that.

**Comment by jrobertson-insite** [comment]
>  Keep an eye out for `list` support within the next couple of months if you're still interested in that.

@briantist are there any updates on the "list" support?

**Comment by briantist** [comment]
@jrobertson-insite clearly my estimation skills leave something to be desired! The refactor that had been going on was very effective though, and as you may have seen we are at the point of moving beyond just the `hashi_vault` plugin into new plugins and modules.

So we're ready to have that support, it's just a matter of writing the content and the tests that go along with it.

We've got `vault_read` and `vault_login` done, `vault_token_create` is in process in #213 , and more on the way. I haven't forgotten about `list` support either, but high on my list are also a generic `vault_write`, and of course kv-specific plugins.

If you'd like to put in an actual feature request issue for tracking it, that'd be fine.
