### ISSUE TITLE
Galaxy link from "About" section in github is misspelled

### ISSUE THREAD

**Issue by dsafanyuk** [ansible-collections/community.hashi_vault#98]
##### SUMMARY
Current link:
http://galaxy.ansible.com/community/hash_vault
Correct Link:
https://galaxy.ansible.com/community/hashi_vault

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
n/a
##### ANSIBLE VERSION
n/a

**Comment by dmsimard** [comment]
Fixed, thanks!

**Comment by dsafanyuk** [comment]
hey @dmsimard not sure if it's caching or something, but it doesn't appear to be fixed:
![image](https://user-images.githubusercontent.com/9590380/122804975-839d8d00-d296-11eb-9220-9a10e8b26535.png)

**Comment by briantist** [comment]
hm, I too see it as broken again. I thought it was fixed when I checked it immediately after the change 🤔

**Comment by briantist** [comment]
@dmsimard no rush of course. 
Could you also change the description to:

> Ansible collection for managing and working with HashiCorp Vault.
> [Ansible Galaxy](https://galaxy.ansible.com/community/hashi_vault)

The current (full link) doesn't even fit on the web version without being truncated.

Thanks!

**Comment by dmsimard** [comment]
@dsafanyuk @briantist that was me being oblivious to the ``s/hash_vault/hashi_vault/`` typo, I had only fixed ``s/http/https/``.

I've fixed the link and adjusted the description.

**Comment by briantist** [comment]
thank you very much @dmsimard !
